### ISSUE TITLE
Some stuff missing

### ISSUE THREAD

**Issue by UtraTM** [Sighmir/vrp_basic_menu#1]
Hello,
getting an error using this. Set the permissions and stuff. But mug and hack doesnt work.
missing fb called cb

and also looks like Service is always on service. or does this not work with the police job?

**Comment by UtraTM** [comment]
Can you help with a readme how to use this stuff correct?
It is really nice stuff inside as i saw in the scripts :)

**Comment by Sighmir** [comment]
I don't have time to fix any issues right now, the buttons use the permissions system. You have to create a group called onservice for on service button to work, and actually implement a check for that group where you need it. For example the missions. I uploaded a version with a quick fix for the lang file, it should fix the mug and hack button. I could make a readme file, but on the vRP github page theres an extensive documentation of how to use it, enough for you to know exactly how to use the vrp_basic_menu.

**Comment by UtraTM** [comment]
Thanks for the stuff. I figured out some of this now.

ONly thing im not clear is the police_weapons how to get it work. Hopefully i can figure it out

**Comment by UtraTM** [comment]
actually im not good in coding but learning more and more. 
but cant get the onservice thing working correct. also the police equip i would love to use.

Can you maybe help with this 2 things to understand the code then?

It would help me a lot

**Comment by Sighmir** [comment]
the onservice button requires the creation of a group on the cfg/groups.lua like this
```
  ["onservice"] = {
    "mission.receive"
  },
```
for the police equip you need to add a static menu at cfg/gui.lua like this:
```
fg.static_menu_types = {
   ["police_weapons"] = {
      title = "Police Weapons",
      blipid = 2, 
      blipcolor = 0,
      permissions = {
        "police.weapons"
      }
    },
   ["emergency_medkit"] = {
      title = "Emergency Medkit",
      blipid = 2, 
      blipcolor = 0,
      permissions = {
        "emergency.medkit"
      }
    }
}

-- list of static menu points
cfg.static_menus = {
  {"police_weapons", 456.85079956055,-988.32708740234,30.689584732056},
  {"emergency_medkit", 458.85079956055,-990.32708740234,30.689584732056}
}
```
add the permission police.weapons to cops and they will be able to get a set of weapons on the locker room for you to check if the user is on a group you can use 
for you to check if the user is on a group you can use 
```
if vRP.hasGroup({user_id,"onservice"}) then
  --do something
end
```
this is mainly made to be used at vrp_basic_mission/server.lua like this:
```
if not vRP.hasMission({player}) and vRP.hasGroup({user_id,"onservice"}) then
```
this way only players on service will get missions. when they go off service they wont and it will cancel the active mission. 
It's not my job to teach you how to use vRP please read the documentation for it at https://github.com/ImagicTheCat/vRP
