### ISSUE TITLE
Not possible to up +$1000 with the fines

### ISSUE THREAD

**Issue by Armagryzor** [Sighmir/vrp_basic_menu#12]
Hi Sighmir ,

The fines system work nice , but it's not possible to give a fine like more than $1000

I tried to modify this piece of code  :

	      if tonumber(fine) > 1000 then
  			    fine = 1000
		      end
		      if tonumber(fine) < 100 then
		        fine = 100
		      end

But no luck....

Thank's

**Comment by Sighmir** [comment]
You just have to change 1000 to the max value:
```
  	      if tonumber(fine) > 5000 then
		    fine = 5000
	      end
	      if tonumber(fine) < 100 then
	        fine = 100
	      end
```

**Comment by Armagryzor** [comment]
Thank's for your quick reply, i 'll test and i'll let you know

**Comment by Sighmir** [comment]
I believe this is working as intended and theres no problem here. I tested it and other people managed to change maximun and minimum amount with success.

**Comment by Armagryzor** [comment]
Work awesome ... Thank you

Excuse me , but is it possible that the cop can receive 10 or 20% of the fines ??

Also big thank you...
