### ISSUE TITLE
Cant get it to work!

### ISSUE THREAD

**Issue by Hjalte3323** [Sighmir/vrp_basic_menu#17]
I added the resoruce, at started it. I writed theese things to groups.lua
		"police.easy_jail",
	"police.easy_unjail",
	"police.easy_fine",
	"police.easy_cuff",
	"police.drag",
    "police.menu"

but it isn't showing the menu on F9 ;(

**Comment by Sighmir** [comment]
The script only works with the latest version of vRP, your version is missing the police menu builder. Or the "police.menu" permission would already be there by default.
