### ISSUE TITLE
[vRPex] Clean install --> Error with vrp_basic_menu

### ISSUE THREAD

**Issue by dylan57700** [Sighmir/vrp_basic_menu#18]
# Main error
`Error running call reference function for resource vrp_basic_menu: citizen:/scripting/lua/scheduler.lua:51: Current execution context is not in the scheduler, you should use CreateThread / SetTimeout or Event system (AddEventHandler) to be able to Await
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:51: in field 'Await'
        @vrp/lib/utils.lua:57: in function <@vrp/lib/utils.lua:56>
        (...tail calls...)
        cfg/menus/main.lua:7: in local 'ref'
        citizen:/scripting/lua/scheduler.lua:317: in function <citizen:/scripting/lua/scheduler.lua:308>
`

# Logs
Full log here: https://pastebin.com/GZ5pr0ri

It happens when I try to open the menu.

# Started ressources (server.cfg)

start mapmanager
start chat
start spawnmanager
start sessionmanager
start fivem
start hardcap
start rconlog
start scoreboard
start playernames

start npc_control

start vrp_mysql
start vrp
start vrp_robbery
start vrp_nocarjack
start vrp_basic_menu
start vrp_esx_phone
start vrp_armorshop

sv_scriptHookAllowed 0

**Comment by Sighmir** [comment]
I just made a commit adding a Citizen Thread to a function, hopefully that fix your issue. 
I can't really reproduce it. It doesn't seem to happen when I open the menu.

**Comment by Sighmir** [comment]
Fixed at https://github.com/Sighmir/vrp_basic_menu/commit/b085a5cdb0b40e75a3743fe773a6f64e0819dbe8
