### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by mrCPUgeek** [Sighmir/vrp_basic_menu#3]
I have vrp_basic_menu in my resources folder and I added it to my server.cfg file. What should I see in game to know that it is working?

(sorry to keep bothering you, but I do love your mods. very nice)

**Comment by Sighmir** [comment]
No worries. 
vrp_basic_menu is a resource that gives you a reserved space where you can create buttons and menus without changing the original vRP files. 
I created a few examples on it and am always taking requests for new functionalities and adding them as I can. 
On the vrp_basic_menu/server.lua, at the bottom part of the file, where I register the buttons and menus you can see the permissions required for each button and a description of what they do. 
The static menus have to be created on the vrp/cfg/gui.lua.
Don't forget to add the permissions on vrp/cfg/groups.lua.

_Sent from my Samsung SM-G900M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
