### ISSUE TITLE
Hack issue

### ISSUE THREAD

**Issue by Armagryzor** [Sighmir/vrp_basic_menu#7]
Hi Sighmir,

Just to says that the hack system have a problem. You can hack a player and receive the dirty money , but no money was deduct on th DBB !!

**Comment by Sighmir** [comment]
Just letting you know that there really is a mistake and I will be releasing a quick fix for it as soon as possible!

**Comment by Armagryzor** [comment]
Thank you for your reply ..Test on your dev server you'll see ;)

Aniway , i know that i'm on the issue board, but i saw that you have a stronger knowloged on VRP. is it possible for you to add a script like your bank but with need 2 or 3 cops to rob bank and if cop is not connected , it will be not possible to rob..

Thank's a lot for your work , i love it!!!

**Comment by Sighmir** [comment]
I stopped working on GTA V scripts for 4 months, and I am not coming back to it for at least the next 2 months.

That resource was made to be used in PvE ( against NPC cops), the PvP version with online cops check will be done once I have time for GTA V scripts again in 2 months.

**Comment by Sighmir** [comment]
Thank you for your help this issue should now be fixed, please if you have any problems comment here, I will leave this open for 7 more days, if I have no answer I will close it and consider it fixed!

**Comment by Armagryzor** [comment]
Work nice now!! Thank you!!
