### ISSUE TITLE
Drag

### ISSUE THREAD

**Issue by DunkoUK** [Sighmir/vrp_basic_menu#9]
Firstly, outstanding work.

Now, I've added police.drag to the cops perms yet it's not coming up in the menu at all? Everything else comes up fine, just not the drag.

Any ideas?

**Comment by Sighmir** [comment]
I cant really tell what is wrong, the quick fix for the button was on the client.lua file so the button should at least show up on the police menu, like it did before. If anything wrong happen it should be after you click the button. Are you using the most original version from vRP from GitHub? My scripts won't work with the "Edited" versions of vRP like Psycho's.

**Comment by DunkoUK** [comment]
Yes they all work and your scripts work with my pack :P 

I'll take a look at what you previously edited in the client.lua, at first glance I notice

"other = nil
drag = false
playerStillDragged = false" are all missing "local" - will have a play.

Side note: I forgot to get permission to put your scripts in my pack and released them today, I did credit you on the FiveM forums. If you want me to remove it just let me know.

I've also got a working Freeze script (stops nearest player moving) on the police menu (added to the client/police.lua & moduels/police.lua), if you want that to put in your vrp_basic_menu?

**Comment by Sighmir** [comment]
These variables don't have local because they are global in the e scope of the resource.

**Comment by DunkoUK** [comment]
Ok weird one, I went fresh with just vrp & your mod. Added just the police.drag and voila it showed up on the menu (Haven't actually tried the function yet as I was solo testing, will let you know the outcome). So I went back to my edit, copied the police.lua's over and started again. It then showed up even in my pack. So I added my Freeze option back in and it didn't show Freeze, just Drag. Do you know if there is a limit for the police menu? That's the only thing I can think of here, works for just one, but not with the other.

**Comment by Sighmir** [comment]
Not sure what you are doing wrong there, I sugest using the vrp_basic_menu to add your freeze command instead of modifying modules files from vRP, I sugest doing every change as resources, I can't account or give support for changes on the code of vRP it self, and strongly advise against it.
